config/routes.rb
Rails.application.routes.draw do
  root to: 'tools#index'

  resources :sites
  resources :tools do
    resources :versions do
      resources :installations
    end
  end

  post '/tools/:tool_id/versions/:version_id/installations/:id',
    to: 'installations#install_one',
    as: 'tool_install_one'

  post '/tools/:tool_id/versions/:version_id',
    to: 'installations#install_all',
    as: 'tool_install_all'
end

app/models/installation.rb
class Installation < ActiveRecord::Base
  belongs_to :site
  belongs_to :version
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true

  validates :install_host, presence: true
  validates :install_path, presence: true

  after_save :create_empty_installations, on: [ :create ]

  protected
  def create_empty_installations
    Version.all.each do |version|
      Installation.create(state: 'uninstalled' , version_id: version.id , site_id: self.id)
    end
  end
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :versions

  validates :name, presence: true
  validates :name, uniqueness: true

  validates :repository_path, presence: true
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :tool
  has_many :installations

  validates :name, presence: true
  validates :name, uniqueness: { scope: :tool }
  validates :name, format: { with: /\Av\d+\.\d+\.\d+\z/,
                             message: "must be of format v<num>.<num>.<num>" }

  validates :release_notes, presence: true
  validates :release_notes, length: {minimum: 24} 

  after_save :create_empty_installations, on: [ :create ]

  protected
  def create_empty_installations
    Site.all.each do |site|
      Installation.create(state: 'uninstalled' , version_id: self.id , site_id: site.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  def install_one
    @tool = Tool.find(params[:tool_id])
    @version = Version.find(params[:version_id])
    @installation = Installation.find(params[:id])

    # FIXME - This is where I do the actual install
 
    respond_to do |format|
      format.js {}
    end

  end

  def install_all
    @tool = Tool.find(params[:tool_id])
    @version = Version.find(params[:version_id])
    @installations = @version.installations

    # FIXME - This is where I do the actual install

    respond_to do |format|
      format.js {}
    end

  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save(site_params)
      redirect_to :sites
    else
      render :new
    end
  end

  private
  def site_params
    params.require(:site).permit(:name, :install_host, :install_path)
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)

    if @tool.save(tool_params)
      redirect_to tools_path
    else
      render :new
    end
  end

  private
  def tool_params
    params.require(:tool).permit(:name, :repository_path)
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def new
    @tool = Tool.find(params[:tool_id])
    @version = Version.new
  end

  def create
    @tool = Tool.find(params[:tool_id])
    @version = @tool.versions.new(version_params)

    if @version.save(version_params)
      redirect_to tools_path
    else
      render :new
    end
  end

  def show
    @version = Version.find(params[:id])
  end

  private
  def version_params
    params.require(:version).permit(:name, :release_notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/installations_helper.rb
module InstallationsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/common/_form_errors.html.haml
- if object.errors.any?
  .error_explanation
    %h3
      = pluralize(object.errors.count, "error")
      prohibited this article from being saved:

    %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/common/_header.html.haml
.jumbotron
  .container
    %h1.text-center Tool Buddy
    %h2.text-center Your Tool Install Homie

.container
  .btn-group.main-menu
    = link_to "Home", tools_path, method: 'get', class: "btn btn-default"
    = link_to "Sites", sites_path, method: 'get', class: "btn btn-default"
    = link_to "Add Site", new_site_path, method: 'get', class: "btn btn-default"
    = link_to "Add Tool", new_tool_path, method: 'get', class: "btn btn-default"

app/views/installations/install_all.html.haml
%h1 Installing at all sites
%h2 Tool: #{@tool.name}
%h2 Version: #{@version.name}
%h2 Installations:
%ul
  - @installations.each do |installation|
    %li #{installation.site.name}

app/views/installations/install_all.js.erb
alert("Performing an install at all sites");

app/views/installations/install_one.html.haml
%h1 Installing at one site
%h2 Tool: #{@tool.name}
%h2 Version: #{@version.name}
%h2 Installation: #{@installation.site.name}

app/views/installations/install_one.js.erb
var current_state_value = $("#state-<%= @installation.id %>").text().trim();
var new_state_value = (current_state_value == 'installed') ? 'uninstalled' : 'installed';
var new_button_value = (current_state_value == 'installed') ? 'Install' : 'Remove';
$("#state-<%= @installation.id %>").html(new_state_value);
$("#install-<%= @installation.id %>").prop('value', new_button_value);

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title ToolBuddy
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'common/header'
    = yield

app/views/sites/index.html.haml
.container
  .page-header
    %h1 All Sites

  %table.table.table-striped.table-border
    %tr
      %th Site Name
      %th Host
      %th Install Path
    - @sites.each do |site|
      %tr
        %td= site.name
        %td= site.install_host
        %td= site.install_path

app/views/sites/new.html.haml
.container
  .page-header
    %h1 Create a new site

  = render partial: 'common/form_errors', locals: {object: @site}

  = form_for(@site) do |f|
    %p
      = f.label :name
      = f.text_field :name
    %p
      = f.label :install_host
      = f.text_field :install_host
    %p
      = f.label :install_path
      = f.text_field :install_path
    %p
      = f.submit

app/views/tools/_single_tool.html.haml
.panel.panel-default
  .panel-heading{ id: "heading-#{tool.id}", role: 'tab'}
    %h4.panel-title 
      .container
        .row
          .col-md-10
            %a{ 'data-toggle' => "collapse",  'data-parent' => "#accordion",  href: "#collapse-#{tool.id}", 'aria-expanded' => "true", 'aria-controls' => "collapse-#{tool.id}"}
              = tool.name 
          .col-md-2
            = button_to 'New Version', new_tool_version_path(tool), method: 'get', class: 'btn btn-default'
  .panel-collapse.collapse{ id: "collapse-#{tool.id}", role: "tabpanel", 'aria-labelledby' => "heading-#{tool.id}" }
    .panel-body
      = render partial: 'version_table', locals: {tool: tool, versions: tool.versions}

app/views/tools/_version_table.html.haml
%table.table.table-striped.table-bordered
  = render partial: 'version_table_header'
  - versions.each do |version|
    = render partial: 'version_table_row', locals: { tool: tool, version: version }

app/views/tools/_version_table_header.html.haml
%tr
  %th Version
  %th Release Notes

app/views/tools/_version_table_row.html.haml
%tr
  %td= link_to version.name, tool_version_path(tool, version)
  %td= version.release_notes

app/views/tools/index.html.haml
.container
  .page-header
    %h1 All Tools
    %h4 (click any tool to see versions)
  .panel-group#accordion{role: 'tablist',  'aria-multiselectable' => 'true'}
    - @tools.each do |tool|
      = render partial: 'single_tool', locals: {tool: tool}

app/views/tools/new.html.haml
.container
  .page-header
    %h1 Create a new tool

  = render partial: 'common/form_errors', locals: {object: @tool}
  = form_for(@tool) do |f|
    %p
      = f.label :name
      = f.text_field :name
    %p
      = f.label :repository_path
      = f.text_field :repository_path
    %p
      = f.submit

app/views/versions/new.html.haml
.container
  .page-header
    %h1 New Tool Version

  = render partial: 'common/form_errors', locals: {object: @version}
  = form_for([@tool, @version]) do |f|
    %p
      = f.label :name
      = f.text_field :name
    %p
      = f.label :release_notes
      = f.text_area :release_notes
    %p
      = f.submit

app/views/versions/show.html.haml
.container

  .page-header
    %h1 Version Information

  .well.version-summary
    %h3
      Tool:
      = @version.tool.name

    %h3
      Version:
      = @version.name

    %h3
      Release Notes:
      = @version.release_notes

  %table.table.table-striped.table.border
    %tr
      %th Site
      %th State
      %th
        = button_to "Install All",
          tool_install_all_path(version_id: @version.id),
          class: "btn btn-default install-all",
          remote: true
    - @version.installations.each do |installation|
      %tr
        %td= installation.site.name
        %td{ id: "state-#{installation.id}"}
          = installation.state
        %td
          = button_to "Install", 
            tool_install_one_path(id: installation.id, version_id: @version.id),
            class: "btn btn-default",
            id: "install-#{installation.id}",
            remote: true